project_name: smtp-edc

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: asachs
    name: smtp-edc
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Version }}"
  footer: |
    ## Installation

    ### Using Homebrew (macOS/Linux)

    ```bash
    brew install asachs/tap/smtp-edc
    ```

    ### Using Scoop (Windows)

    ```powershell
    scoop bucket add asachs https://github.com/asachs/scoop-bucket.git
    scoop install smtp-edc
    ```

    ### Manual Installation

    1. Download the appropriate binary for your platform from the assets below
    2. Extract the archive
    3. Move the binary to a directory in your PATH
    4. Make the binary executable (Unix-like systems only) 