repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
    -   id: golangci-lint
        args: [--fast]

-   repo: local
    hooks:
    -   id: go-test
        name: go test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false

    -   id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false

    -   id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false
