# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SmtpEdc < Formula
  desc "A powerful, cross-platform SMTP testing tool written in Go"
  homepage "https://github.com/asachs01/smtp-edc"
  version "1.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/asachs01/smtp-edc/releases/download/v1.2.0/smtp-edc_Darwin_x86_64.tar.gz"
    sha256 "087f36c0ac6b0153faa3e937c9bd3815304ade50adb44749b0bfa98f77e5d788"

    def install
      bin.install "smtp-edc"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the SmtpEdc
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/asachs01/smtp-edc/releases/download/v1.2.0/smtp-edc_Linux_x86_64.tar.gz"
        sha256 "3f4e6489523c597d5e75e42107e69efc54d445dea6e7e22bcb9e19156699d841"

        def install
          bin.install "smtp-edc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/asachs01/smtp-edc/releases/download/v1.2.0/smtp-edc_Linux_arm64.tar.gz"
        sha256 "83a18923f14087d4393f492989972a3fc226e0856150a2cefa1cc15c4ae3a749"

        def install
          bin.install "smtp-edc"
        end
      end
    end
  end

  test do
    system "#{bin}/smtp-edc --version"
  end
end
