// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDefaultTemplates() {
  return window['go']['main']['App']['CreateDefaultTemplates']();
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExecuteTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteTemplate'](arg1, arg2, arg3);
}

export function GetAuthStats() {
  return window['go']['main']['App']['GetAuthStats']();
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetDebugMode() {
  return window['go']['main']['App']['GetDebugMode']();
}

export function GetDefaultConfigPath() {
  return window['go']['main']['App']['GetDefaultConfigPath']();
}

export function GetDefaultTemplates() {
  return window['go']['main']['App']['GetDefaultTemplates']();
}

export function GetTemplateDirectory() {
  return window['go']['main']['App']['GetTemplateDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConfigFiles() {
  return window['go']['main']['App']['ListConfigFiles']();
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function LoadTemplate(arg1) {
  return window['go']['main']['App']['LoadTemplate'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTemplate'](arg1, arg2);
}

export function SendEmail(arg1) {
  return window['go']['main']['App']['SendEmail'](arg1);
}

export function SetDebugMode(arg1) {
  return window['go']['main']['App']['SetDebugMode'](arg1);
}

export function SetTemplateDirectory(arg1) {
  return window['go']['main']['App']['SetTemplateDirectory'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ValidateConfig(arg1) {
  return window['go']['main']['App']['ValidateConfig'](arg1);
}

export function ValidateEmailAddress(arg1) {
  return window['go']['main']['App']['ValidateEmailAddress'](arg1);
}

export function ValidateEmailList(arg1, arg2) {
  return window['go']['main']['App']['ValidateEmailList'](arg1, arg2);
}

export function ValidateTemplate(arg1) {
  return window['go']['main']['App']['ValidateTemplate'](arg1);
}
