// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateDefaultTemplates():Promise<services.TemplateResult>;

export function DeleteTemplate(arg1:string):Promise<services.TemplateResult>;

export function ExecuteTemplate(arg1:string,arg2:string,arg3:services.TemplateData):Promise<services.EmailRequest>;

export function GetAuthStats():Promise<Record<string, any>>;

export function GetCurrentConfig():Promise<services.ConfigData>;

export function GetDebugMode():Promise<boolean>;

export function GetDefaultConfigPath():Promise<string>;

export function GetDefaultTemplates():Promise<Record<string, string>>;

export function GetTemplateDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListConfigFiles():Promise<Array<string>>;

export function ListTemplates():Promise<Array<services.TemplateInfo>>;

export function LoadConfig(arg1:string):Promise<services.ConfigData>;

export function LoadTemplate(arg1:string):Promise<services.TemplateResult>;

export function SaveConfig(arg1:services.ConfigData,arg2:string):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<services.TemplateResult>;

export function SendEmail(arg1:services.EmailRequest):Promise<services.SendResult>;

export function SetDebugMode(arg1:boolean):Promise<void>;

export function SetTemplateDirectory(arg1:string):Promise<void>;

export function TestConnection(arg1:services.ConfigData):Promise<services.ConnectionResult>;

export function ValidateConfig(arg1:services.ConfigData):Promise<void>;

export function ValidateEmailAddress(arg1:string):Promise<services.SendResult>;

export function ValidateEmailList(arg1:Array<string>,arg2:boolean):Promise<services.SendResult>;

export function ValidateTemplate(arg1:string):Promise<services.TemplateResult>;
