name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o smtp-edc-linux-amd64 ./cmd/smtp-edc
          GOOS=linux GOARCH=arm64 go build -o smtp-edc-linux-arm64 ./cmd/smtp-edc

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o smtp-edc-darwin-amd64 ./cmd/smtp-edc
          GOOS=darwin GOARCH=arm64 go build -o smtp-edc-darwin-arm64 ./cmd/smtp-edc

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o smtp-edc-windows-amd64.exe ./cmd/smtp-edc
          GOOS=windows GOARCH=arm64 go build -o smtp-edc-windows-arm64.exe ./cmd/smtp-edc

      - name: Generate changelog
        run: |
          echo "## What's Changed" > CHANGELOG.tmp
          git log --pretty=format:"* %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.tmp
          echo "" >> CHANGELOG.tmp
          echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/$(git describe --tags --abbrev=0 HEAD^)...${GITHUB_REF#refs/tags/}" >> CHANGELOG.tmp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.tmp
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            smtp-edc-linux-amd64
            smtp-edc-linux-arm64
            smtp-edc-darwin-amd64
            smtp-edc-darwin-arm64
            smtp-edc-windows-amd64.exe
            smtp-edc-windows-arm64.exe

      - name: Publish to Go package registry
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${GITHUB_REF#refs/tags/} 